{% set name = "dandischema" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9f69a4c6e779be99f5e1ffd82402e824f9e319afedf7ae3db877e7d78d5c9ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioningit
  run:
    - python >={{ python_min }}
    - email-validator >=1.0.3
    - jsonschema
    - packaging >=14.0
    - pydantic >=2.4,<3
    - pydantic-settings
    - requests
    - rfc3987
    - zarr-checksum

test:
  requires:
    - anys
    - pytest
    - pytest-cov
    - pytest-rerunfailures
    - python {{ python_min }}
  source_files:
    - tox.ini
  imports:
    - dandischema
  commands:
    - python -m pytest -vv --pyargs dandischema

about:
  home: https://github.com/dandi/dandischema
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Schemata for DANDI archive project
  description: |
    A Python library for maintaining and managing DANDI metadata schemata. The
    library helps create and validate DANDI schema-compliant metadata for
    Dandisets and assets.
  dev_url: https://github.com/dandi/dandischema

extra:
  recipe-maintainers:
    - yarikoptic
